// Static NS station data — embedded to avoid runtime API dependency
// Source: OpenStreetMap / NS open data
const STATIONS_DATA = [
  // ── Megastations ──────────────────────────────────────────────────────────
  { code:'ASD',  name:'Amsterdam Centraal',           type:'megastation',               lat:52.3791, lng: 4.8990 },
  { code:'RTD',  name:'Rotterdam Centraal',           type:'megastation',               lat:51.9249, lng: 4.4699 },
  { code:'UT',   name:'Utrecht Centraal',             type:'megastation',               lat:52.0893, lng: 5.1101 },
  { code:'GVC',  name:'Den Haag Centraal',            type:'megastation',               lat:52.0805, lng: 4.3249 },
  { code:'SHL',  name:'Amsterdam Airport Schiphol',   type:'megastation',               lat:52.3095, lng: 4.7623 },

  // ── Knooppunt intercitystations ───────────────────────────────────────────
  { code:'ASDM', name:'Amsterdam Amstel',             type:'knooppuntIntercitystation', lat:52.3465, lng: 4.9184 },
  { code:'ASS',  name:'Amsterdam Sloterdijk',         type:'knooppuntIntercitystation', lat:52.3888, lng: 4.8371 },
  { code:'ASA',  name:'Amsterdam Zuid',               type:'knooppuntIntercitystation', lat:52.3389, lng: 4.8728 },
  { code:'AMF',  name:'Amersfoort',                   type:'knooppuntIntercitystation', lat:52.1534, lng: 5.3752 },
  { code:'AH',   name:'Arnhem Centraal',              type:'knooppuntIntercitystation', lat:51.9849, lng: 5.8998 },
  { code:'BD',   name:'Breda',                        type:'knooppuntIntercitystation', lat:51.5958, lng: 4.7800 },
  { code:'GVS',  name:'Den Haag HS',                  type:'knooppuntIntercitystation', lat:52.0698, lng: 4.3243 },
  { code:'DV',   name:'Deventer',                     type:'knooppuntIntercitystation', lat:52.2584, lng: 6.1593 },
  { code:'DT',   name:'Dordrecht',                    type:'knooppuntIntercitystation', lat:51.8120, lng: 4.6692 },
  { code:'EHV',  name:'Eindhoven',                    type:'knooppuntIntercitystation', lat:51.4435, lng: 5.4794 },
  { code:'ES',   name:'Enschede',                     type:'knooppuntIntercitystation', lat:52.2225, lng: 6.8935 },
  { code:'GN',   name:'Groningen',                    type:'knooppuntIntercitystation', lat:53.2108, lng: 6.5652 },
  { code:'HLM',  name:'Haarlem',                      type:'knooppuntIntercitystation', lat:52.3878, lng: 4.6378 },
  { code:'LDN',  name:'Leiden Centraal',              type:'knooppuntIntercitystation', lat:52.1664, lng: 4.4815 },
  { code:'MT',   name:'Maastricht',                   type:'knooppuntIntercitystation', lat:50.8510, lng: 5.7074 },
  { code:'NM',   name:'Nijmegen',                     type:'knooppuntIntercitystation', lat:51.8432, lng: 5.8525 },
  { code:'HT',   name:"'s-Hertogenbosch",             type:'knooppuntIntercitystation', lat:51.6921, lng: 5.2934 },
  { code:'TB',   name:'Tilburg',                      type:'knooppuntIntercitystation', lat:51.5597, lng: 5.0820 },
  { code:'VL',   name:'Venlo',                        type:'knooppuntIntercitystation', lat:51.3717, lng: 6.1730 },
  { code:'ZL',   name:'Zwolle',                       type:'knooppuntIntercitystation', lat:52.5050, lng: 6.0940 },

  // ── Intercitystations ─────────────────────────────────────────────────────
  { code:'ALM',  name:'Almere Centrum',               type:'intercitystation',          lat:52.3743, lng: 5.2176 },
  { code:'ALMB', name:'Almere Buiten',                type:'intercitystation',          lat:52.3889, lng: 5.2671 },
  { code:'APD',  name:'Apeldoorn',                    type:'intercitystation',          lat:52.2074, lng: 5.9692 },
  { code:'ASB',  name:'Amsterdam Bijlmer ArenA',      type:'intercitystation',          lat:52.3131, lng: 4.9472 },
  { code:'ASSP', name:'Amsterdam Science Park',       type:'intercitystation',          lat:52.3567, lng: 4.9480 },
  { code:'AMRI', name:'Amersfoort Schothorst',        type:'intercitystation',          lat:52.1779, lng: 5.3699 },
  { code:'BRN',  name:'Barneveld Noord',              type:'intercitystation',          lat:52.1624, lng: 5.5736 },
  { code:'CRTD', name:'Castricum',                    type:'intercitystation',          lat:52.5456, lng: 4.6613 },
  { code:'DD',   name:'Delft',                        type:'intercitystation',          lat:52.0065, lng: 4.3573 },
  { code:'DDRS', name:'Delft Zuid',                   type:'intercitystation',          lat:51.9850, lng: 4.3568 },
  { code:'DVST', name:'Deventer Colmschate',          type:'intercitystation',          lat:52.2580, lng: 6.2174 },
  { code:'DV',   name:'Deventer',                     type:'knooppuntIntercitystation', lat:52.2584, lng: 6.1593 },
  { code:'EDE',  name:'Ede-Wageningen',               type:'intercitystation',          lat:52.0472, lng: 5.6651 },
  { code:'EM',   name:'Emmen',                        type:'intercitystation',          lat:52.7785, lng: 6.8953 },
  { code:'GD',   name:'Gouda',                        type:'intercitystation',          lat:52.0179, lng: 4.7082 },
  { code:'GDG',  name:'Gouda Goverwelle',             type:'intercitystation',          lat:52.0248, lng: 4.7419 },
  { code:'GL',   name:'Geldermalsen',                 type:'intercitystation',          lat:51.8854, lng: 5.2796 },
  { code:'GVC',  name:'Den Haag Centraal',            type:'megastation',               lat:52.0805, lng: 4.3249 },
  { code:'HFD',  name:'Hoofddorp',                    type:'intercitystation',          lat:52.3028, lng: 4.6916 },
  { code:'HGL',  name:'Helmond',                      type:'intercitystation',          lat:51.4808, lng: 5.6622 },
  { code:'HR',   name:'Heerlen',                      type:'intercitystation',          lat:50.8882, lng: 5.9764 },
  { code:'HRN',  name:'Hoorn',                        type:'intercitystation',          lat:52.6432, lng: 5.0570 },
  { code:'HRNK', name:'Hoorn Kersenboogerd',          type:'intercitystation',          lat:52.6579, lng: 5.0687 },
  { code:'KW',   name:'Kampen',                       type:'intercitystation',          lat:52.5578, lng: 5.9127 },
  { code:'LAA',  name:'Den Haag Laan v NOI',          type:'intercitystation',          lat:52.0963, lng: 4.3444 },
  { code:'LEDN', name:'Leiden Lammenschans',          type:'intercitystation',          lat:52.1499, lng: 4.4833 },
  { code:'LLS',  name:'Lelystad Centrum',             type:'intercitystation',          lat:52.5183, lng: 5.4751 },
  { code:'MB',   name:'Middelburg',                   type:'intercitystation',          lat:51.4985, lng: 3.6130 },
  { code:'MDB',  name:'Middelburg',                   type:'intercitystation',          lat:51.4985, lng: 3.6130 },
  { code:'MP',   name:'Meppel',                       type:'intercitystation',          lat:52.6966, lng: 6.1960 },
  { code:'OVN',  name:'Oss',                          type:'intercitystation',          lat:51.7707, lng: 5.5193 },
  { code:'PT',   name:'Purmerend',                    type:'intercitystation',          lat:52.5055, lng: 4.9549 },
  { code:'RSD',  name:'Roosendaal',                   type:'intercitystation',          lat:51.5300, lng: 4.4636 },
  { code:'RTTA', name:'Rotterdam Alexander',          type:'intercitystation',          lat:51.8872, lng: 4.5857 },
  { code:'RTB',  name:'Rotterdam Blaak',              type:'intercitystation',          lat:51.9200, lng: 4.4837 },
  { code:'SC',   name:'Schiedam Centrum',             type:'intercitystation',          lat:51.9173, lng: 4.4007 },
  { code:'SN',   name:'Sneek',                        type:'intercitystation',          lat:53.0326, lng: 5.6599 },
  { code:'SWK',  name:'Steenwijk',                    type:'intercitystation',          lat:52.7877, lng: 6.1129 },
  { code:'TBG',  name:'Tilburg Universiteit',         type:'intercitystation',          lat:51.5628, lng: 5.0449 },
  { code:'VDK',  name:'Veenendaal-De Klomp',          type:'intercitystation',          lat:52.0291, lng: 5.5486 },
  { code:'VTN',  name:'Veenendaal Centrum',           type:'intercitystation',          lat:52.0293, lng: 5.5567 },
  { code:'WD',   name:'Woerden',                      type:'intercitystation',          lat:52.0881, lng: 4.8803 },
  { code:'WP',   name:'Weesp',                        type:'intercitystation',          lat:52.3088, lng: 5.0434 },
  { code:'ZD',   name:'Zoetermeer',                   type:'intercitystation',          lat:52.0542, lng: 4.4924 },
  { code:'ZL',   name:'Zwolle',                       type:'knooppuntIntercitystation', lat:52.5050, lng: 6.0940 },
  { code:'ZVT',  name:'Zevenaar',                     type:'intercitystation',          lat:51.9302, lng: 6.0700 },

  // ── Stoptreinstation (selection of well-known stops) ─────────────────────
  { code:'AC',   name:'Alkmaar',                      type:'stoptreinstation',          lat:52.6378, lng: 4.7418 },
  { code:'ALKO', name:'Alkmaar Noord',                type:'stoptreinstation',          lat:52.6543, lng: 4.7459 },
  { code:'AKM',  name:'Akkrum',                       type:'stoptreinstation',          lat:53.0479, lng: 5.8436 },
  { code:'AMFS', name:'Amersfoort Vathorst',          type:'stoptreinstation',          lat:52.1999, lng: 5.3814 },
  { code:'ASD',  name:'Amsterdam Centraal',           type:'megastation',               lat:52.3791, lng: 4.8990 },
  { code:'ASDL', name:'Amsterdam Lelylaan',           type:'stoptreinstation',          lat:52.3570, lng: 4.8373 },
  { code:'ASDO', name:'Amsterdam Muiderpoort',        type:'stoptreinstation',          lat:52.3617, lng: 4.9354 },
  { code:'ASDRA',name:'Amsterdam Ravel',              type:'stoptreinstation',          lat:52.3295, lng: 4.9394 },
  { code:'ASDS', name:'Amsterdam Centraal',           type:'stoptreinstation',          lat:52.3780, lng: 4.8990 },
  { code:'ASDW', name:'Amsterdam De Vlugtlaan',       type:'stoptreinstation',          lat:52.3765, lng: 4.8445 },
  { code:'ASDZ', name:'Amsterdam Zuid',               type:'stoptreinstation',          lat:52.3389, lng: 4.8728 },
  { code:'ATO',  name:'Almelo',                       type:'stoptreinstation',          lat:52.3561, lng: 6.6604 },
  { code:'BKL',  name:'Barendrecht',                  type:'stoptreinstation',          lat:51.8564, lng: 4.5382 },
  { code:'BN',   name:'Boxtel',                       type:'stoptreinstation',          lat:51.5988, lng: 5.3207 },
  { code:'BTL',  name:'Benthuizen',                   type:'stoptreinstation',          lat:52.0503, lng: 4.5405 },
  { code:'CPS',  name:'Capelle Schollevaar',          type:'stoptreinstation',          lat:51.9345, lng: 4.5679 },
  { code:'DMS',  name:'Doetinchem',                   type:'stoptreinstation',          lat:51.9616, lng: 6.2961 },
  { code:'DN',   name:'Deurne',                       type:'stoptreinstation',          lat:51.4657, lng: 5.8126 },
  { code:'DRDL', name:'Dordrecht Zuid',               type:'stoptreinstation',          lat:51.7930, lng: 4.6656 },
  { code:'DRN',  name:'Dronten',                      type:'stoptreinstation',          lat:52.5259, lng: 5.7213 },
  { code:'EHB',  name:'Eindhoven Beukenlaan',         type:'stoptreinstation',          lat:51.4565, lng: 5.4600 },
  { code:'EHBO', name:'Eindhoven Strijp-S',           type:'stoptreinstation',          lat:51.4395, lng: 5.4604 },
  { code:'EHJV', name:'Eindhoven Woensel',            type:'stoptreinstation',          lat:51.4614, lng: 5.4853 },
  { code:'FL',   name:'Franeker',                     type:'stoptreinstation',          lat:53.1888, lng: 5.5432 },
  { code:'GB',   name:'Gennep',                       type:'stoptreinstation',          lat:51.6993, lng: 5.9762 },
  { code:'GNB',  name:'Groningen Europapark',         type:'stoptreinstation',          lat:53.2100, lng: 6.5903 },
  { code:'GNP',  name:'Grou-Jirnsum',                 type:'stoptreinstation',          lat:53.1011, lng: 5.8479 },
  { code:'GNW',  name:'Groningen Noord',              type:'stoptreinstation',          lat:53.2266, lng: 6.5569 },
  { code:'GPD',  name:'Gorredijk',                    type:'stoptreinstation',          lat:53.0060, lng: 6.0622 },
  { code:'HAL',  name:'Harlingen Haven',              type:'stoptreinstation',          lat:53.1770, lng: 5.4190 },
  { code:'HDE',  name:'Harderwijk',                   type:'stoptreinstation',          lat:52.3557, lng: 5.6253 },
  { code:'HDT',  name:'Hengelo',                      type:'stoptreinstation',          lat:52.2616, lng: 6.7979 },
  { code:'HK',   name:'Heerhugowaard',                type:'stoptreinstation',          lat:52.6665, lng: 4.8372 },
  { code:'HN',   name:'Hoorn',                        type:'stoptreinstation',          lat:52.6432, lng: 5.0570 },
  { code:'HOO',  name:'Hoogeveen',                    type:'stoptreinstation',          lat:52.7252, lng: 6.4789 },
  { code:'HS',   name:'Den Haag Hollands Spoor',      type:'stoptreinstation',          lat:52.0698, lng: 4.3243 },
  { code:'HVS',  name:'Hilversum',                    type:'stoptreinstation',          lat:52.2214, lng: 5.1789 },
  { code:'KMP',  name:'Kampen Zuid',                  type:'stoptreinstation',          lat:52.5400, lng: 5.9211 },
  { code:'KRD',  name:'Kerkrade Centrum',             type:'stoptreinstation',          lat:50.8659, lng: 6.0618 },
  { code:'LDL',  name:'Leiderdorp',                   type:'stoptreinstation',          lat:52.1555, lng: 4.5044 },
  { code:'LWD',  name:'Leeuwarden',                   type:'stoptreinstation',          lat:53.1968, lng: 5.7931 },
  { code:'NDB',  name:'Nieuw-Den Helder',             type:'stoptreinstation',          lat:52.9538, lng: 4.7620 },
  { code:'NDB',  name:'Den Helder',                   type:'stoptreinstation',          lat:52.9538, lng: 4.7620 },
  { code:'ND',   name:'Den Helder',                   type:'stoptreinstation',          lat:52.9538, lng: 4.7620 },
  { code:'NMB',  name:'Nijmegen Heyendaal',           type:'stoptreinstation',          lat:51.8289, lng: 5.8686 },
  { code:'NMD',  name:'Nijmegen Dukenburg',           type:'stoptreinstation',          lat:51.8106, lng: 5.8094 },
  { code:'NNS',  name:'Nunspeet',                     type:'stoptreinstation',          lat:52.3845, lng: 5.7770 },
  { code:'OH',   name:'Oldenzaal',                    type:'stoptreinstation',          lat:52.3085, lng: 6.9305 },
  { code:'ONK',  name:'Ommen',                        type:'stoptreinstation',          lat:52.5174, lng: 6.4205 },
  { code:'OV',   name:'Overveen',                     type:'stoptreinstation',          lat:52.4024, lng: 4.6203 },
  { code:'PBD',  name:'Purmerend Overwhere',          type:'stoptreinstation',          lat:52.5196, lng: 4.9715 },
  { code:'RL',   name:'Roermond',                     type:'stoptreinstation',          lat:51.1951, lng: 5.9832 },
  { code:'RM',   name:'Rhenen',                       type:'stoptreinstation',          lat:51.9640, lng: 5.5701 },
  { code:'RTD',  name:'Rotterdam Centraal',           type:'megastation',               lat:51.9249, lng: 4.4699 },
  { code:'RTDS', name:'Rotterdam Stadion',            type:'stoptreinstation',          lat:51.8936, lng: 4.5205 },
  { code:'RZB',  name:'Raalte',                       type:'stoptreinstation',          lat:52.3905, lng: 6.2741 },
  { code:'SD',   name:'Sittard',                      type:'stoptreinstation',          lat:51.0022, lng: 5.8740 },
  { code:'SG',   name:'Stavoren',                     type:'stoptreinstation',          lat:52.8892, lng: 5.3631 },
  { code:'SKW',  name:'Stadskanaal',                  type:'stoptreinstation',          lat:52.9846, lng: 6.9506 },
  { code:'SLO',  name:'Sloterdijk',                   type:'stoptreinstation',          lat:52.3888, lng: 4.8371 },
  { code:'STD',  name:'Sittard',                      type:'stoptreinstation',          lat:51.0022, lng: 5.8740 },
  { code:'TBR',  name:'Tilburg Reeshof',              type:'stoptreinstation',          lat:51.5428, lng: 4.9943 },
  { code:'TD',   name:'Tiel',                         type:'stoptreinstation',          lat:51.8922, lng: 5.4295 },
  { code:'TW',   name:'Twello',                       type:'stoptreinstation',          lat:52.2361, lng: 6.1089 },
  { code:'UO',   name:'Utrecht Overvecht',            type:'stoptreinstation',          lat:52.1159, lng: 5.1178 },
  { code:'UTL',  name:'Utrecht Leidsche Rijn',        type:'stoptreinstation',          lat:52.0821, lng: 5.0611 },
  { code:'UTM',  name:'Utrecht Maliebaan',            type:'stoptreinstation',          lat:52.0930, lng: 5.1299 },
  { code:'UTP',  name:'Utrecht Padualaan',            type:'stoptreinstation',          lat:52.0820, lng: 5.1282 },
  { code:'VB',   name:'Venray',                       type:'stoptreinstation',          lat:51.5312, lng: 5.9757 },
  { code:'VK',   name:'Venlo',                        type:'stoptreinstation',          lat:51.3717, lng: 6.1730 },
  { code:'VLT',  name:'Vlissingen',                   type:'stoptreinstation',          lat:51.4480, lng: 3.5724 },
  { code:'VS',   name:'Velsen-IJmuiden',              type:'stoptreinstation',          lat:52.4644, lng: 4.6178 },
  { code:'VSMR', name:'Valkenburg',                   type:'stoptreinstation',          lat:50.8672, lng: 5.8256 },
  { code:'WF',   name:'Wolvega',                      type:'stoptreinstation',          lat:52.8754, lng: 5.9955 },
  { code:'WO',   name:'Winterswijk',                  type:'stoptreinstation',          lat:51.9703, lng: 6.7201 },
  { code:'WR',   name:'Weert',                        type:'stoptreinstation',          lat:51.2472, lng: 5.7011 },
  { code:'ZK',   name:'Zutphen',                      type:'stoptreinstation',          lat:52.1477, lng: 6.1950 },
  { code:'ZTM',  name:'Zoetermeer',                   type:'stoptreinstation',          lat:52.0542, lng: 4.4924 },
  { code:'ZVS',  name:'Zevenaar',                     type:'stoptreinstation',          lat:51.9302, lng: 6.0700 },
  { code:'ZWN',  name:'Zwolle',                       type:'stoptreinstation',          lat:52.5050, lng: 6.0940 },
];
